### ISSUE TITLE
Redo this repo like the others

### ISSUE THREAD

**Issue by codefromthecrypt** [WebAssembly/wasi-handle-index#4]
It is hard to tell what this repository aims to be. It would be nice for this to have a README that elaborates this and similar contents to wasi-filesystem

**Comment by sunfishcode** [comment]
This repo has turned out to no longer be needed and I'm in the [process of removing it](https://github.com/WebAssembly/WASI/pull/507). I've now replaced the old contents with a minimal README.md and will archive the repo.
